# Project: Project
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = src/main.o
LINKOBJ  = src/main.o
LIBS     = -L"E:/hoc/App/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"E:/hoc/App/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc -L"E:/hoc/App/PROJECT/lib" -mwindows -lraylib -lopengl32 -lgdi32 -lwinmm -pg
INCS     = -I"E:/hoc/App/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"E:/hoc/App/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/hoc/App/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/hoc/App/PROJECT/include"
CXXINCS  = -I"E:/hoc/App/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"E:/hoc/App/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"E:/hoc/App/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"E:/hoc/App/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++" -I"E:/hoc/App/PROJECT/include"
BIN      = Project.exe
CXXFLAGS = $(CXXINCS) -pg -std=c++17 -s -static  -fext-numeric-literals -lraylib -lopengl32 -lgdi32 -lwinmm
CFLAGS   = $(INCS) -pg
DEL      = E:\hoc\App\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

src/main.o: src/main.cpp
	$(CPP) -c src/main.cpp -o src/main.o $(CXXFLAGS)
